#!/bin/bash

# Add your backup dir location, password, mysql location and mysqldump location
DATE=$(date +%d-%m-%Y)
BACKUP_DIR="/home/radiant/Desktop"
MYSQL_USER="root"
MYSQL_PASSWORD="."

# To create a new directory into backup directory location
mkdir -p $BACKUP_DIR/$DATE

# get a list of databases with out information schema
#databases=`mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema)"`
# get a list of databases   
databases=`mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e "SHOW DATABASES;" | grep -Ev "(Database)"`

# dump each database in separate name
for db in $databases; do
echo $db
mysqldump --force --opt --user=$MYSQL_USER -p$MYSQL_PASSWORD --all-databases  | gzip > "$BACKUP_DIR/$DATE/$db.sql.gz"
#mysqldump --force --opt --user=$MYSQL_USER -p$MYSQL_PASSWORD --databases $db | gzip > "$BACKUP_DIR/$DATE/$db.sql.gz"
done

# Delete files older than 10 days
#find $BACKUP_DIR/* -mtime +10 -exec rm {} \;
